# Generated by Django 6.0.4 on 2026-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('freelancer', 'Freelancer')], default='freelancer', max_length=20),
        ),
    ]
