# Generated by Django 6.0.3 on 2026-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_userprofile_created_at_userprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('freelancer', 'Freelancer')], max_length=20),
        ),
    ]
