# Generated by Django 5.2.3 on 2026-06-29 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_invoice_google_drive_url_lpo_google_drive_url_and_more'),
        ('tasks', '0013_workrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests', to='sales.quotation'),
        ),
    ]
