# Generated by Django 6.0.3 on 2026-03-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_due_date_invoice_notes_invoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='attention',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
