# Generated by Django 6.0.3 on 2026-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_invoice_attention_invoice_sales_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
