# Generated by Django 6.0.3 on 2026-03-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_paymentreceipt_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trn_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
