# Generated by Django 6.0.3 on 2026-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_customer_trn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
