# Generated by Django 6.0.3 on 2026-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_supplier_alter_lpo_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
