# Generated by Django 6.0.3 on 2026-04-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_supplier_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
