# Generated by Django 6.0.3 on 2026-04-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_supplier_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpoitem',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
