# Generated by Django 6.0.3 on 2026-04-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_lpoitem_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpo',
            name='quote_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
