# Generated by Django 6.0.3 on 2026-05-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_lpo_quote_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='lpo',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.supplier'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
    ]
